[build]
  command = "npm run build"
  functions = "functions-build"  # Change this from "functions" to "functions-build"
  publish = "public"

[build.environment]
  NODE_VERSION = "14"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200