[build]
  command = "npm run build"
  functions = "functions-build"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/ar-server/:splat"
  status = 200

[functions]
  directory = "functions"

[dev]
  command = "npm start"